version: '3'

services:
  web:
    build: backend/.
    env_file:
      - env_private/web.env
      - env_private/db.env
    environment:
      - DJANGO_DEBUG=false
    volumes:
      - ./backend:/usr/src/hardware_inventory
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - env_private/db.env
