version: '3'

services:
  web:
#    build: backend/.
#    env_file:
#      - env_private/web.env
#      - env_private/db.env
#    environment:
#      - DJANGO_DEBUG=false
#    volumes:
#      - ./backend:/usr/src/hardware_inventory
#    depends_on:
#      - db
    networks:
      - db_network
      - nginx_network

  db:
#    image: postgres
#    env_file:
#      - env_private/db.env
    networks:
      - db_network

  proxy:
    image: nginx:1.17
    volumes:
    - ./proxy:/etc/nginx/conf.d
    ports:
      - 8765:80
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
